import React, { useState } from "react";
import {
  scaleLinear,
  scaleTime,
  timeFormat,
  extent,
  bin,
  timeMonths,
  sum,
  // select,
} from "d3";
import { useData } from "./useData";
import { AxisBottom } from "./AxisBottom";
import { AxisLeft } from "./AxisLeft";
import { Marks } from "./Marks";
import ReactDropdown from "react-dropdown";

// const svg = select("#graph-container").append("svg").attr("height", 200);

const width = 1000 
const height = 540;
const margin = { top: 20, right: 30, bottom: 65, left: 90 };
const xAxisLabelOffset = 50;
const yAxisLabelOffset = 60;

const attributes = [
  { value: "cost", label: "Our Cost" },
  { value: "price", label: "Our Price" },
  { value: "retailPrice", label: "Retail Price" },
  { value: "created", label: "Date Created" },
  // { value: "date", label: "date" }, //Date is not in the db
];
//^ GETTING CURRENT MONTH
const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
const d = new Date();
const monthName = months[d.getMonth()]; // "July" (or current month)

// FUNCTION TO GET LABEL
const getLabel = (value) => {
  for (let i = 0; i < attributes.length; i++) {
    if (attributes[i].value === value) {
      return attributes[i].label;
    }
  }
};

const ScatterPlot = () => {
  const data = useData();

  const initialXAttribute = "created";
  const [xAttribute, setXAttribute] = useState(initialXAttribute);
  const xValue = (d) => d.created;
  const xAxisLabel = getLabel(xAttribute);

  console.log(typeof d.created);
  const initialYAttribute = "cost";
  const [yAttribute, setYAttribute] = useState(initialYAttribute);
  const yValue = (d) => d[yAttribute];
  const yAxisLabel = getLabel(yAttribute);

  if (!data) {
    return <pre>Loading...</pre>;
  }

  const innerHeight = height - margin.top - margin.bottom;
  const innerWidth = width - margin.left - margin.right;

  const xAxisTickFormat = timeFormat("%m/%d");

  const padding = 60;
  const mindate = new Date(2021, 3, 1), //Indexed: therefore 3 is really the 4th month (April)
    maxdate = new Date(2021, 3, 31);

  const xScale = scaleTime()
    .domain([mindate, maxdate])
    .range([padding, width - padding]);

  // Date is undefined when using the below xScale (Was trying to get a range of first ever created data to last)
  // const xScale = scaleTime()
  //   .domain(extent(data, xValue))
  //   .range([0, innerWidth])
  //   .nice();
  //   console.log(xScale.domain(), xScale.range())

  //Destructuring start and stop from domain
  const [start, stop] = xScale.domain();

  const binnedData = bin()
    .value(xValue) //Value accessor (returns the date)
    .domain(xScale.domain()) //Setting domain to extent of dates (min and max dates)
    .thresholds(timeMonths(start, stop))(data) //Setting thresholds of bin generator to be all months between start and stop (computed above from xScale.domain())
    //Then passing original data into the above bin generator
    //Bin generator returns the array of arrays that we're working with
    .map((array) => ({
      //Processing each of the inner arrays (all events happening in any given month)
      //Each of these arrays is transformed into an object containing x0 (date), and x1 (end date) generated by the bin generator
      y: sum(array, yValue), // Total Dead and Missing over each months array
      mindate: array.created, //Start date range
      // x1: array.maxdate, //End date range
    })); //return of this .map is assigned to binnedData
  console.log(start);
  const yScale = scaleLinear()
    .domain(extent(data, yValue))
    .range([innerHeight, 0])
    .nice();

  // const colorScale = scaleOrdinal()
  //   .domain(data.map(colorValue))
  //   .range(["#e6842a", "#137b80", "#8e6c8a"]);

  return (
    <>
      <div className="sales-graph-container" id="graph-container">
        <div className="sales-graph">
          <p className="sales-graph-date-range">{monthName} 2021 insights</p>
          <div className="menus-container">
            <span className="dropdown-label">Y</span>
            <ReactDropdown
              options={attributes}
              value={yAttribute}
              onChange={({ value }) => setYAttribute(value)}
            />
          </div>
          <div className="body-center">
            <svg viewBox="0 0 1000 540">
              <g transform={`translate(${margin.left},${margin.top})`}>
                <AxisBottom
                  xScale={xScale}
                  innerHeight={innerHeight}
                  tickFormat={xAxisTickFormat}
                  // dateValue={dateValue}
                />
                <text
                  className="axis-label"
                  textAnchor="middle"
                  transform={`translate(${-yAxisLabelOffset},${
                    innerHeight / 2
                  }) rotate(-90)`}
                  tickOffset={4}
                >
                  {yAxisLabel}
                </text>
                <AxisLeft yScale={yScale} innerWidth={innerWidth} />
                <text
                  className="axis-label"
                  x={innerWidth / 2}
                  y={innerHeight + xAxisLabelOffset}
                  textAnchor="middle"
                  tickOffset={5}
                >
                  {xAxisLabel}
                </text>
                <Marks
                  binnedData={binnedData}
                  xScale={xScale}
                  xValue={xValue}
                  yScale={yScale}
                  yValue={yValue}
                  // colorScale={colorScale}
                  // colorValue={colorValue}
                  tooltipFormat={xAxisTickFormat}
                  mindate={mindate}
                  maxdate={maxdate}
                />
              </g>
            </svg>
          </div>
        </div>
      </div>
    </>
  );
};
export default ScatterPlot;
